### ISSUE TITLE
Repo initialization

### ISSUE THREAD

**Issue by shuowu** [shuowu/Orion#1]
@jichao06  I will setup wiki about code commit practice later. Add whatever you want to clarify tasks, like wiki, issues, etc.

I am planning to keep this repo public for now, then make it private when needed.(For money consideration :-) )

**Comment by jichao06** [comment]
OK.

I won't worry about the private repo yet. What we will be doing for now isn't much secret. Amazon is releasing a new Cloud service called CodeCommit which is better integrated to other AWS service. This should come very soon. We can then decide which one to use.

**Comment by jichao06** [comment]
Lets come up a code name for the project instead of using TopicNews.

**Comment by jichao06** [comment]
We will use code name Orion for now.
