### ISSUE TITLE
Create a prototype web page using sample topic file

### ISSUE THREAD

**Issue by jichao06** [shuowu/Orion#6]
A sample topic file has been checked in at python/experiment/data/test_topics.json.

The json object has the following format:

{
    "topics": [ <List of word for a topic> ...]
    "stories":[ <text for each story>...]
    "topic_stories":[<dict of story index and its weight for the topic> ...]
    "story_topics":[<dict of topic index and the story's weight for the topic> ...]
}

where topics is index by its position in 'topics" list
and stories is indexed by its position in 'stories" list

Using this sample topic file, a prototype web page need to be built to demonstrate UI design ideas.

**Comment by shuowu** [comment]
@jichao06  My idea is to format the son like:
{
topicIndexes: [url1, url2 .., urln], //This part can be used to load topics first, the array can contains a                     //bunch of simple topic object with URL in it. After topics loaded, stories can be loaded asyncly. UI non-block.
topics: [
  topic1: {
    story1: {...},
    story2: {....},
    ...
    storyn: {...}.
  },
  topic2: {...},
  ..
  topicn: {}..
]
}

Reason for this format is front-end should focus on how UI is generated, manipulate all DOM element, instead computing data. I will upload some sample son files later
